version: '3'

services:
  web:
    image: sparql_monitoring_tool_ui
    deploy:
      restart_policy:
        condition: any
        delay: 60s
      labels:
        - traefik.frontend.rule=Host:$FRONTEND_HOST
        - traefik.docker.network=traefik
        - traefik.port=8080
        - traefik.protocol=http
        - traefik.enable=true
        - traefik.tags=traefik
        - traefik.redirectorservice.frontend.entryPoints=http
        - traefik.redirectorservice.frontend.redirect.entryPoint=https
        - traefik.webservice.frontend.entryPoints=https
    networks:
      - traefik
    environment:
      - REACT_APP_API_GATEWAY=https://$FRONTEND_HOST
      - REACT_APP_HOST_ENV=https://$FRONTEND_HOST$FRONTEND_HOST_PREFIX


networks:
  traefik:
    external: true
