const EndpointTypes ={
    SET_ALL: 'SET_ALL',
    ADD_ENDPOINT: 'ADD_ENDPOINT',
    REMOVE_ENDPOINT: 'REMOVE_ENDPOINT',
    SET_ENDPOINT: 'SET_ENDPOINT',
    EDIT_ENDPOINT: 'EDIT_ENDPOINT'
}

export default EndpointTypes;